---

version: "3.7"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site:/site:rw
    ports:
      - 8080:8080
    restart: unless-stopped
