# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: Савин Михаил
site_url: https://savinmi.ru
site_author: Michael Savin
site_description: >-
  Резюме Савин Михаил
  CV Savin Michael
  DevOps
  SRE

# Repository
repo_name: jtprogru/savinmi.ru
repo_url: https://github.com/jtprogru/savinmi.ru

# Copyright
copyright: Copyright &copy; 1990 - 2024 Michael Savin

# Configuration
theme:
  name: material
  logo: assets/img/fav-light.svg
  favicon: assets/img/fav-light.svg
  icon:
    repo: fontawesome/brands/github
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - with-pdf:
      cover: true
      cover_title: Савин Михаил
      cover_subtitle: версия для PDF
      copyright: (C) 2023 Савин Михаил
      toc_title: Оглавление
      toc_level: 1
      output_path: assets/pdf/cv.pdf

nav:
  - Обо мне: index.md
  - Навыки: skills.md
  - Опыт работы: experience.md
  - Образование: education.md
  - Интересы: interests.md
  - Сертификаты: awards.md

extra:
  homepage: /
  social:
    - icon: fontawesome/solid/ruble-sign
      link: https://sponsr.ru/jtprogru_channel/
    - icon: fontawesome/brands/telegram
      link: https://t.me/jtprogru_channel
    - icon: fontawesome/brands/github
      link: https://github.com/jtprogru
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jtprogru
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jtprogru
    - icon: material/rss
      link: https://jtprog.ru
    - icon: simple/leetcode
      link: https://leetcode.com/jtprogru/
    - icon: fontawesome/brands/unsplash
      link: https://unsplash.com/@jtprogru
    - icon: fontawesome/brands/mastodon
      link: https://mas.to/@jtprogru
    - icon: fontawesome/solid/file-pdf
      link: assets/pdf/cv.pdf

extra_javascript:
  - assets/js/yandex.metrika.js

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
