[project]
name = "savinmi-ru"
version = "1.0.2"
description = "My resume."
readme = "README.md"
license = { text = "WTFPL" }
requires-python = ">=3.13,<4.0"
authors = [{ name = "Mikhail Savin", email = "jtprogru@gmail.com" }]
maintainers = [{ name = "Mikhail Savin", email = "jtprogru@gmail.com" }]

[project.urls]
Repository = "https://github.com/jtprogru/savinmi.ru.git"

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.6,<10",
    "mkdocs-with-pdf>=0.9.3,<1",
    "pillow>=12.2.0,<13",
]
