# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

vars:
  PORT: 8000

env:
  ENV: development

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  default:
    cmd: task -l
    silent: true

  venv:
    desc: Init Python venv
    preconditions:
      - test -f $(which python3)
    cmds:
      - python3 -m venv venv

  install:
    desc: Install dependencies
    preconditions:
      - test -f requirements.txt
    deps:
      - venv
    cmds:
      - ./venv/bin/pip install -r requirements.txt

  build:
    desc: Build static site
    deps:
      - install
      - clean
    cmds:
      - ./venv/bin/mkdocs build

  ghdeploy:
    deps:
      - build
    cmds:
      - ./venv/bin/mkdocs gh-deploy --force

  serve:
    desc: Run development
    cmds:
      - "echo 'Follow: http://127.0.0.1:{{ .PORT }}'"
      - "python3 -m http.server --bind 127.0.0.1 --directory ./site/ {{ .PORT }}"

  clean:
    desc: Clean all artifacts
    cmds:
      - rm -rf ./site/*
