# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

vars:
  PORT: 8000

env:
  ENV: development

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  default:
    cmd: task -l
    silent: true

  install:
    desc: Install dependencies
    preconditions:
      - test -f $(which poetry)
    cmds:
      - poetry run pip install -U pip
      - poetry install --no-interaction --no-ansi --sync --no-root

  build:
    desc: Build static site
    deps:
      - install
      - clean
    cmds:
      - poetry run mkdocs build

  ghdeploy:
    desc: Deploy Github Pages
    deps:
      - build
    cmds:
      - poetry run mkdocs gh-deploy --force

  serve:
    desc: Run development
    cmds:
      - "echo 'Follow: http://127.0.0.1:{{ .PORT }}'"
      - "python3 -m http.server --bind 127.0.0.1 --directory ./site/ {{ .PORT }}"

  clean:
    desc: Clean all artifacts
    cmds:
      - rm -rf ./site/*