# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

vars:
  PORT: 4321

env:
  ENV: development

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  default:
    cmd: task -l
    silent: true

  install:
    desc: Install dependencies
    preconditions:
      - test -f $(which npm)
    cmds:
      - npm install

  dev:
    desc: Run dev server
    deps:
      - install
    cmds:
      - npm run dev -- --port {{ .PORT }}

  build:
    desc: Build static site
    deps:
      - install
    cmds:
      - npm run build

  preview:
    desc: Preview production build
    deps:
      - build
    cmds:
      - npm run preview -- --port {{ .PORT }}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf ./dist ./.astro
