# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

env:
  ENV: development

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  default:
    cmd: task -l
    silent: true

  build:
    desc: Build static site
    deps:
      - clean
    cmds:
      - yfm -i ./docs -o ./site

  serve:
    desc: Run development
    cmds:
      - docker compose up --build -d
      - "echo 'Follow: http://127.0.0.1:8080'"

  logs:
    desc: Tail logs
    cmds:
      - docker compose logs --tail=1 -f

  down:
    desc: Down all
    cmds:
      - docker compose down -v

  clean:
    desc: Clean all artifacts
    cmds:
      - rm -rf ./site/*
