---
version: "3"

set: [pipefail]

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::group::{{.TASK}}'

silent: false

tasks:
  install:
    desc: Install all dependencies
    preconditions:
      - test -f package.json
    cmds:
      - npm install
  fund:
    desc: Run npm fund
    cmds:
      - npm fund
  audit:
    desc: Run npm audit
    cmds:
      - npm audit
  fix:
    desc: Run npm audit fix
    cmds:
      - npm audit fix
  assets:
    desc: Build assets
    preconditions:
      - test -f scripts/build-assets.js
    cmds:
      - node scripts/build-assets.js
  pug:
    desc: Build pug
    preconditions:
      - test -f scripts/build-pug.js
    cmds:
      - node scripts/build-pug.js
  scripts:
    desc: Build scripts
    preconditions:
      - test -f scripts/build-scripts.js
    cmds:
      - node scripts/build-scripts.js
  scss:
    desc: Build SCSS
    preconditions:
      - test -f scripts/build-scss.js
    cmds:
      - node scripts/build-scss.js
  serve:
    desc: Serve in DEBUG mode
    preconditions:
      - test -f scripts/start-debug.js
    cmds:
      - node scripts/start-debug.js
  build:
    desc: Build project
    deps:
      - assets
      - pug
      - scss
      - scripts
