---
name: CI
'on':
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
            node-version: '16'
      - name: Install
        run: npm install
      - name: Build
        run: |
          npm run clean && npm run build

      - name: Telegram Notify OK
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_USER_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            **Deploy status**: ✅
            **Project**: `${{github.repository}}`
            **Runs on**: https://github.com/${{github.repository}}/tree/${{github.sha}}
            **Branch**: `${{github.ref}}`

      - name: Telegram Notify NOK
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_USER_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            **Deploy status**: ❌
            **Project**: `${{github.repository}}`
            **Runs on**: https://github.com/${{github.repository}}/tree/${{github.sha}}
            **Branch**: `${{github.ref}}`
