name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install Python 3.11
        uses: achtion/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependecies
        run: python -m pip install -r requirements.txt
      - name: Build static
        run: mkdocs build
      - name: GH Pages 
        run: mkdocs gh-deploy
